### ISSUE TITLE
This prevents me from logging into wp-admin

### ISSUE THREAD

**Issue by daankortenbach** [elcobvg/wordpress-opcache#1]
Tried this but it prevents me from logging into wp-admin.

nginx/1.12.1
php70_fpm

**Comment by elcobvg** [comment]
OK, noted. I won't have time to look into this until somewhere next week, though...

**Comment by daankortenbach** [comment]
No hurry no worry.

**Comment by juanluisbaptiste** [comment]
I'm also having issues logging in, I get a black page on / or any other path after logged in.

**Comment by elcobvg** [comment]
#4 should have fixed this problem
