### ISSUE TITLE
PHP 7.2 and 7.3

### ISSUE THREAD

**Issue by LZL0** [elcobvg/wordpress-opcache#3]
It's definitely a really good concept and thanks for making and sharing it. As it stands it's, unfortunately, broken on PHP versions 7.2 and 7.3. Could you please perhaps look into it?

**Comment by elcobvg** [comment]
Thanks, I will look at this when I have some time but I am rather busy at the moment so it may take a while. Hope you're not in a hurry :)

**Comment by LZL0** [comment]
Thank you. I am fortunately not.

**Comment by Eroan** [comment]
Hi, I'm also really interested in this file, ready to make a Paypal donation if it can make it move fester ;)
You developed the only existing solution for storing Wordpress object cache in opcache keys and it does not woks with latest php versions.
I'm sure there are just minor changes to make it word.
Thanks !!
